# Generated by Django 6.0.6 on 2026-07-23 12:11

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='limit_amount',
            new_name='budget_amount',
        ),
        migrations.AddField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'month', 'year')},
        ),
    ]
