# Generated by Django 6.0.6 on 2026-07-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_remove_report_user_expense_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default='Expense', max_length=200),
            preserve_default=False,
        ),
    ]
